In [8]:
import os

import pandas as pd

path = r"E:\2026년\1. 초장대 K-지하고속도로 인프라 안전 및 효율 향상 기술 개발\VISSIM_Workspace\Test"
mer_list = sorted([file for file in os.listdir(path) if file.endswith(".parquet")])
print(mer_list)
for idx, start in enumerate(range(0, len(mer_list))):
    file = os.path.join(path, mer_list[idx])
    print(file)
    df=pd.read_parquet(file)
    display(df)

['화성~서울(140-진입구간)_260518_001.parquet', '화성~서울(140-진입구간)_260518_002.parquet', '화성~서울(140-진입구간)_260518_003.parquet']
E:\2026년\1. 초장대 K-지하고속도로 인프라 안전 및 효율 향상 기술 개발\VISSIM_Workspace\Test\화성~서울(140-진입구간)_260518_001.parquet

,Measurem.,t(Entry),t(Exit),VehNo,Vehicle type,Line,v[km/h],b[m/s2],Occ,Pers,tQueue,VehLength[m],Unnamed: 12
0,10001,1800.03,-1.00,826,100,0,92.7,-0.06,0.07,1,0.0,4.76,NaN
1,10039,-1.00,1800.09,747,100,0,86.2,-0.13,0.09,1,0.0,4.64,NaN
2,10060,1800.02,-1.00,706,100,0,85.6,0.39,0.08,1,0.0,4.61,NaN
3,10066,1800.09,-1.00,689,100,0,87.0,-0.17,0.01,1,0.0,4.21,NaN
4,10074,1800.05,-1.00,671,100,0,86.7,0.20,0.05,1,0.0,4.76,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2436896,20095,13199.99,-1.00,5986,300,0,85.0,0.18,0.01,1,0.0,12.40,NaN
2436897,20135,13200.00,-1.00,5903,100,0,86.7,-0.26,0.00,1,0.0,4.21,NaN
2436898,20161,13199.97,-1.00,5848,100,0,85.0,-0.21,0.03,1,0.0,4.01,NaN
2436899,20179,13199.95,-1.00,5816,100,0,84.8,0.20,0.05,1,0.0,4.01,NaN
2436900,20208,13199.93,-1.00,5756,100,0,85.4,-0.06,0.07,1,0.0,4.61,NaN

E:\2026년\1. 초장대 K-지하고속도로 인프라 안전 및 효율 향상 기술 개발\VISSIM_Workspace\Test\화성~서울(140-진입구간)_260518_002.parquet

,Measurem.,t(Entry),t(Exit),VehNo,Vehicle type,Line,v[km/h],b[m/s2],Occ,Pers,tQueue,VehLength[m],Unnamed: 12
0,10048,-1.00,1800.03,714,650,0,67.9,0.19,0.03,1,0.0,10.21,NaN
1,10062,1800.00,-1.00,705,630,0,83.7,0.20,0.10,1,0.0,10.21,NaN
2,10107,1800.05,-1.00,614,100,0,86.7,-0.09,0.05,1,0.0,4.21,NaN
3,10118,1800.05,-1.00,588,100,0,85.6,0.16,0.05,1,0.0,4.21,NaN
4,10184,1800.00,-1.00,470,100,0,85.7,-0.21,0.10,1,0.0,4.21,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2430380,20207,-1.00,13199.92,5915,100,0,87.4,-0.15,0.02,1,0.0,4.76,NaN
2430381,20211,13199.94,-1.00,5669,100,0,86.2,-0.18,0.06,1,0.0,4.01,NaN
2430382,20223,13199.96,-1.00,5908,100,0,84.3,0.02,0.04,1,0.0,4.01,NaN
2430383,20254,13199.99,-1.00,5588,100,0,85.7,0.26,0.01,1,0.0,4.61,NaN
2430384,99903,13199.97,-1.00,5855,630,0,80.0,-0.24,0.03,1,0.0,10.21,NaN

E:\2026년\1. 초장대 K-지하고속도로 인프라 안전 및 효율 향상 기술 개발\VISSIM_Workspace\Test\화성~서울(140-진입구간)_260518_003.parquet

,Measurem.,t(Entry),t(Exit),VehNo,Vehicle type,Line,v[km/h],b[m/s2],Occ,Pers,tQueue,VehLength[m],Unnamed: 12
0,10017,1800.08,-1.00,808,100,0,84.4,-0.16,0.02,1,0.0,4.61,NaN
1,10034,1800.06,-1.00,778,100,0,86.0,-0.01,0.04,1,0.0,4.64,NaN
2,10060,1800.01,-1.00,723,100,0,86.5,-0.23,0.09,1,0.0,4.64,NaN
3,10091,1800.07,-1.00,653,300,0,84.8,-0.27,0.03,1,0.0,12.40,NaN
4,10147,1800.07,-1.00,540,300,0,85.4,-0.21,0.03,1,0.0,12.40,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2382771,20187,-1.00,13199.94,5685,100,0,85.4,0.16,0.04,1,0.0,4.76,NaN
2382772,20201,13199.93,-1.00,5660,100,0,84.8,0.14,0.07,1,0.0,4.76,NaN
2382773,20221,13199.91,-1.00,5616,100,0,85.9,0.14,0.09,1,0.0,4.61,NaN
2382774,20245,13199.91,-1.00,5562,100,0,83.7,-0.18,0.09,1,0.0,4.36,NaN
2382775,20260,-1.00,13199.96,5764,100,0,86.0,-0.00,0.06,1,0.0,4.21,NaN