In [4]:
import os
import pandas as pd

path = r"C:\Vissim_Workspace\시나리오(140-유고지점 Uniform Random)_260518\진입구간\화성~서울(140-진입구간)_260518_001.parquet"
mer_path = r"C:\Vissim_Workspace\시나리오(140-유고지점 Uniform Random)_260518\진입구간\화성~서울(140-진입구간)_260518_001.mer"
df=pd.read_parquet(path)
display(df)


with open(mer_path, "r", encoding="utf-8", errors="ignore") as file:
            lines = file.readlines()

            data_start_idx = None
            for j, line in enumerate(lines):
                if "Measurem." in line:
                    data_start_idx = j
                    break

            # 데이터프레임 생성
            if data_start_idx is not None:

                # 컬럼명 추출 및 공백 제거
                columns = [col.strip() for col in lines[data_start_idx].strip().split(";")]

                # 데이터 부분 추출 및 가공
                data_lines = lines[data_start_idx + 1:]  # 컬럼명 제외, 데이터 부분
                data = [line.strip().split(";") for line in data_lines if line.strip()]

                # 데이터프레임 생성
                mer_df = pd.DataFrame(data, columns=columns)
                display("mer_df : ", mer_df)

,Measurem.,t(Entry),t(Exit),VehNo,Vehicle type,Line,v[km/h],b[m/s2],Occ,Pers,tQueue,VehLength[m],Unnamed: 12
0,10001,1800.03,-1.00,826,100,0,92.7,-0.06,0.07,1,0.0,4.76,NaN
1,10039,-1.00,1800.09,747,100,0,86.2,-0.13,0.09,1,0.0,4.64,NaN
2,10060,1800.02,-1.00,706,100,0,85.6,0.39,0.08,1,0.0,4.61,NaN
3,10066,1800.09,-1.00,689,100,0,87.0,-0.17,0.01,1,0.0,4.21,NaN
4,10074,1800.05,-1.00,671,100,0,86.7,0.20,0.05,1,0.0,4.76,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2436896,20095,13199.99,-1.00,5986,300,0,85.0,0.18,0.01,1,0.0,12.40,NaN
2436897,20135,13200.00,-1.00,5903,100,0,86.7,-0.26,0.00,1,0.0,4.21,NaN
2436898,20161,13199.97,-1.00,5848,100,0,85.0,-0.21,0.03,1,0.0,4.01,NaN
2436899,20179,13199.95,-1.00,5816,100,0,84.8,0.20,0.05,1,0.0,4.01,NaN
2436900,20208,13199.93,-1.00,5756,100,0,85.4,-0.06,0.07,1,0.0,4.61,NaN

'mer_df : '

,Measurem.,t(Entry),t(Exit),VehNo,Vehicle type,Line,v[km/h],b[m/s2],Occ,Pers,tQueue,VehLength[m],
0,10001,1800.03,-1.00,826,100,0,92.7,-0.06,0.07,1,0.0,4.76,
1,10039,-1.00,1800.09,747,100,0,86.2,-0.13,0.09,1,0.0,4.64,
2,10060,1800.02,-1.00,706,100,0,85.6,0.39,0.08,1,0.0,4.61,
3,10066,1800.09,-1.00,689,100,0,87.0,-0.17,0.01,1,0.0,4.21,
4,10074,1800.05,-1.00,671,100,0,86.7,0.20,0.05,1,0.0,4.76,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2436896,20095,13199.99,-1.00,5986,300,0,85.0,0.18,0.01,1,0.0,12.40,
2436897,20135,13200.00,-1.00,5903,100,0,86.7,-0.26,0.00,1,0.0,4.21,
2436898,20161,13199.97,-1.00,5848,100,0,85.0,-0.21,0.03,1,0.0,4.01,
2436899,20179,13199.95,-1.00,5816,100,0,84.8,0.20,0.05,1,0.0,4.01,
2436900,20208,13199.93,-1.00,5756,100,0,85.4,-0.06,0.07,1,0.0,4.61,